export const VERSION = "1.18.2";
export const isF2E = true;
const DOCUMENT_URL = isF2E
  ? "https://aomi.yuque.com/docs/share/2a5932c8-d1c2-4d0e-90ef-d7c9777ed86f?#"
  : "https://aomi.yuque.com/staff-rimeff/wi9qad/xg4fcq";
const WORK_SITES = new Map([
  ["email", "https://exmail.qq.com/login"],
  ["TB", "https://www.teambition.com/organization/5b023ca7da41b800017b3574"],
  ["aomi-gitlab", "http://github.miguatech.com/"],
  ["aomi-yapi", "http://yapi.miguatech.com/"],
  ["语雀", "https://aomi.yuque.com/"],
  ["维格", "https://vika.cn/workbench/fodQLd56RYNFa"],
  ["项目地址", "https://aomi.yuque.com/ep7275/woyyt7/zunzyk#WvFo"],
  [
    "支付测试账号",
    "https://aomi.yuque.com/books/share/2ea2d186-c82f-493f-8ca1-cd34cad494d6/gui4yv",
  ],
  ["澳觅私服", "http://registry.aomiapp.com/"],
  [
    "澳觅APP下载(安卓)",
    "http://www.pgyer.com/androidAoMiTest?sig=r%2BcYTm0Uk5%2FA9%2FcY8S7IpZW7CYoLm53x0S1WL0f4OYWFkypC7NutVE9Sikwdw6oY",
  ],
  ["澳觅APP下载(IOS)", "https://www.pgyer.com/AomiUserProduct2"],
  ["澳觅商户APP下载(安卓)", "https://www.pgyer.com/androidAomiMerchant"],
  [
    "澳觅商户APP下载(IOS)",
    "https://apps.apple.com/cn/app/%E6%BE%B3%E8%A6%93%E5%95%86%E5%AE%B6/id1147908183",
  ],
  ["澳觅云效流水线", "https://flow.aliyun.com/groups/16510?page=1"],
  [
    "aliyun",
    "https://cs.console.aliyun.com/?spm=5176.b93921871.top-nav.2.b74116d0UZaL2y#/k8s/cluster/cf93fe1dde8584346a2d81575c79aff9e/v2/workload/deployment/list?type=deployment&clusterType=Kubernetes&profile=&state=running&region=cn-shenzhen&ns=aomi",
  ],
]);

const AOMI_SITES = new Map([
  [
    "管理后台",
    [
      [
        "http://test-admin.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1533771/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/r7BdK0uGeIGHZVQNcjq6",
      ],
      [
        "http://uat-admin.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1533927/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/zjfte0WZznf0iskCxxXN",
      ],
      [
        "http://sit-admin.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1534155/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/g5ofE5DPQKIRIkdinFkq",
      ],
      [
        "https://admin.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1534426/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/MVbdobeazHNDnyYRp0fs",
      ],
    ],
  ],
  [
    "直播后台",
    [
      [
        "http://test-live-admin.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1611972/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/a7YEfORiopqEY4MBW9ib",
      ],
      [
        "http://uat-live-admin.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1611992/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/MdeCeINh0NlZFZ4aOsf5",
      ],
      [
        "https://live-admin.aomiapp.com/gray",
        "https://flow.aliyun.com/pipelines/1612004/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/qKDmY6ahN7HHK0HdgvTy",
      ],
      [
        "https://live-admin.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1612006/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/solg1Z7hLJ556M8abeyA",
      ],
    ],
  ],
  [
    "商户后台",
    [
      [
        "http://test-merchant.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1533757/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/138QyhMYJXroqVenaC1T",
      ],
      [
        "http://uat-merchant.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1534024/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/aoCMprGqyNt8ufuQfuEs",
      ],
      [
        "http://sit-merchant.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1534153/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/zUE4ebcYfwdFfqgwgTJl",
      ],
      [
        "https://merchant.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1534412/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/VvFzCavjmDedaOwMs3b8",
      ],
    ],
  ],
  [
    "调度后台",
    [
      [
        "http://web.newrider.miguatech.com",
        "https://flow.aliyun.com/pipelines/1533752/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/Jx6Yfw7GhjxASLg7wuIh",
      ],
      [
        "http://uat-webrider.miguatech.com",
        "https://flow.aliyun.com/pipelines/1534015/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/VLPU3pYfUffYVPkRA7Kb",
      ],
      [
        "http://gray.riderweb.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1534138/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/shPfc3sV1MfSGzZUhCHu",
      ],
      [
        "https://riderweb.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1534404/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/OkXigtZSTXJGPzT90j1F",
      ],
    ],
  ],
  [
    "团餐企业后台",
    [
      [
        "https://test-hk-groupmeal-admin.aomiapp.com/",
        "https://flow.aliyun.com/pipelines/2185786/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/SgCl91djDqjUEeL36vU0",
      ],
      [
        "https://uat-hk-groupmeal-admin.aomiapp.com/",
        "https://flow.aliyun.com/pipelines/2207757/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/OHb7CUlmQ2PvdI5t3HYo",
      ],
      [
        "https://gray-hk-groupmeal-admin.aomiapp.com/",
        "https://flow.aliyun.com/pipelines/2232846/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/lFIrdOozIxIolRmxhEHJ",
      ],
      [
        "https://hk-groupmeal-admin.aomiapp.com/",
        "https://flow.aliyun.com/pipelines/2239127/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/rc3gOb1yOTkN1JUW38hF",
      ],
    ],
  ],
  [
    "权限中心",
    [
      [
        "https://test-authcenter.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1533753/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/atb0Q9VRnCFCpRpRCeel",
      ],
      [
        "https://uat-authcenter.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1534029/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/7bVdOSfaaS6EVULXsRoA",
      ],
      [
        "https://sit-authcenter.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1534145/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/CdEK3ncWYTyaE9P4hhjz",
      ],
      [
        "https://authcenter.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1534422/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/GIvxQWafHlaIb85SEqrG",
      ],
    ],
  ],
  [
    "activity",
    [
      [
        "http://test-h5.aomiapp.com/multiple/",
        "https://flow.aliyun.com/pipelines/1533728/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/Hw2vVsA0i8WO5G6zx7nW",
      ],
      [
        "http://test-h5.aomiapp.com/uat/multiple",
        "https://flow.aliyun.com/pipelines/1533987/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/zhJ7QgWEMKaSrNKAMINZ",
      ],
      [
        "https://h5.aomiapp.com/gray/multiple/",
        "https://flow.aliyun.com/pipelines/1534133/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/cJoXQalzfpRCl7u8EAwD",
      ],
      [
        "https://h5.aomiapp.com/multiple/",
        "https://flow.aliyun.com/pipelines/1534398/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/4CTxkOhJw7EFAlpEqOmV",
      ],
    ],
  ],
  [
    "activity-v2",
    [
      [
        "http://test-h5.aomiapp.com/multiple/",
        "https://flow.aliyun.com/pipelines/1795827/current",
        "",
      ],
      [
        "http://test-h5.aomiapp.com/uat/multiple",
        "https://flow.aliyun.com/pipelines/1795828/current",
        "",
      ],
      [
        "https://h5.aomiapp.com/gray/multiple/",
        "https://flow.aliyun.com/pipelines/1816826/current",
        "",
      ],
      [
        "https://h5.aomiapp.com/multiple/",
        "https://flow.aliyun.com/pipelines/1891258/current",
        "",
      ],
    ],
  ],
  [
    "activity-ssr",
    [
      [
        "http://",
        "https://flow.aliyun.com/pipelines/1533614/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/RcRH4jNE25hxSpqUCbuZ",
      ],
      [
        "http://",
        "https://flow.aliyun.com/pipelines/1533820/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/2PXNBphpzcIPpdmUecMm",
      ],
      ["https://", "https://flow.aliyun.com/pipelines/1674488/current", "null"],
      ["https://", "https://flow.aliyun.com/pipelines/1674502/current", "null"],
    ],
  ],
  [
    "merchant-app",
    [
      [
        "http://",
        "https://flow.aliyun.com/pipelines/1533723/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/qsvt115y4YudZ4zPxadW",
      ],
      [
        "http://",
        "https://flow.aliyun.com/pipelines/1533966/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/nWlXSiDUxqtOj8wHBYx5",
      ],
      [
        "https://",
        "https://flow.aliyun.com/pipelines/1534098/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/S9zArWVqxwVzr3s3KGb3",
      ],
      [
        "https://",
        "https://flow.aliyun.com/pipelines/1534261/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/7CEvIrL4Lk8n73U5uUYp",
      ],
    ],
  ],
  [
    "澳觅商城",
    [
      [
        "https://test-ssr.aomiapp.com/frontend/supermarket/homepage",
        "https://flow.aliyun.com/pipelines/1533700/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/jXRGyRXHQ8Lt2IPghPLy",
      ],
      [
        "https://uat-ssr.aomiapp.com/frontend/supermarket/homepage",
        "https://flow.aliyun.com/pipelines/1533947/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/7bYdmbJKqYp8EcgDpbmj",
      ],
      [
        "https://gray-ssr.aomiapp.com/frontend/supermarket/homepage",
        "https://flow.aliyun.com/pipelines/1534070/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/zBczfWhYEeRSPkYjYfc2",
      ],
      [
        "https://ssr.aomiapp.com/frontend/supermarket/homepage",
        "https://flow.aliyun.com/pipelines/1534221/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/zlrT4qD8Jz407MDRLCxt",
      ],
    ],
  ],
  [
    "biz",
    [
      [
        "http://test-h5.aomiapp.com/long/",
        "https://flow.aliyun.com/pipelines/1533742/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/l1riW7rgs2Y0H2KLItvM",
      ],
      [
        "http://test-h5.aomiapp.com/uat/long/",
        "https://flow.aliyun.com/pipelines/1533976/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/O8XoSuhGV3MDeDEzw0e0",
      ],
      [
        "https://h5.aomiapp.com/gray/long/",
        "https://flow.aliyun.com/pipelines/1534117/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/3koW0TNFSblANfWXGtBq",
      ],
      [
        "https://h5.aomiapp.com/long/",
        "https://flow.aliyun.com/pipelines/1534386/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/2VETPBLvNDAqNHZb0eaT",
      ],
    ],
  ],
  [
    "long-biz",
    [
      [
        "http://test-h5.aomiapp.com/long/",
        "https://flow.aliyun.com/pipelines/1533734/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/mdrjRhwNflogJkprwjG1",
      ],
      [
        "http://test-h5.aomiapp.com/uat/long/",
        "https://flow.aliyun.com/pipelines/1533969/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/3HDiKxJqWUqJfWVaZSW8",
      ],
      [
        "https://h5.aomiapp.com/gray/long/",
        "https://flow.aliyun.com/pipelines/1534111/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/7mNzgb8rWAs3VUXND84E",
      ],
      [
        "https://h5.aomiapp.com/long/",
        "https://flow.aliyun.com/pipelines/1534381/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/ZsKldDagBhw1XSw3NNyx",
      ],
    ],
  ],
  [
    "spa",
    [
      ["http://test-h5.aomiapp.com/spa/", "flow", "null"],
      [
        "http://test-h5.aomiapp.com/uat/spa/",
        "https://flow.aliyun.com/pipelines/1533981/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/Zg4TqYQWQPp9XpBl0KCV",
      ],
      [
        "https://h5.aomiapp.com/gray/spa/",
        "https://flow.aliyun.com/pipelines/1534123/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/eSt5KT5EpXYViU1G6Cmx",
      ],
      [
        "https://h5.aomiapp.com/spa/",
        "https://flow.aliyun.com/pipelines/1534393/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/ThQHjjv2WPOL1oHcIgad",
      ],
    ],
  ],
  [
    "lifepay",
    [
      [
        "http://test-lifepay.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1882983/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/HCSKD6PSPwGE7cuB1MG3",
      ],
      [
        "http://uat-lifepay.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1882978/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/XE4T22PsV81PlaUgt6Ul",
      ],
      [
        "https://gray-lifepay.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1883118/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/QPM5nztKbfmT6FqiUkhK",
      ],
      [
        "https://lifepay.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1883136/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/vM9H14A0VDAyzOOYTTjn",
      ],
    ],
  ],
  [
    "lifepay管理后台",
    [
      [
        "http://test-pay-manager.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1533610/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/EbRWozMXnj0wiqmo2cQ7",
      ],
      [
        "http://uat-pay-manager.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1533935/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/XlPNES9zHkdlJQiAKHQ6",
      ],
      [
        "https://gray-pay-manager.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1534059/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/5aZhVbXkekfgZ9y2uqbz",
      ],
      [
        "https://pay-manager.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1534363/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/Jr1XFhJermihBHbbkwBV",
      ],
    ],
  ],
  [
    "datame",
    [
      [
        "http://test-datame.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1937615/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/Fby1hQL8vX64ArP8SiTc",
      ],
      [
        "http://uat-datame.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1926771/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/P2Rq7Eq3CgdE3rgHZCKf",
      ],
      ["http://gray-datame.aomiapp.com", ""],
      [
        "http://datame.aomiapp.com",
        "https://flow.aliyun.com/pipelines/1940957/current",
        "http://flow-openapi.aliyun.com/pipeline/webhook/gMKAPK7C7HSXdnRX7T61",
      ],
    ],
  ],
  [
    "报表后台",
    [
      ["http://test.report.miguatech.com", ""],
      ["http://uat-report.miguatech.com", ""],
      ["https://gray-report.miguatech.com", ""],
      ["https://new-report.miguatech.com", ""],
    ],
  ],
  [
    "工银券包H5",
    [
      [
        "http://test-h5icbc.miguatech.com",
        "https://flow.aliyun.com/pipelines/1533647/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/D1WUDGDyH158qXWxyKcv",
      ],
    ],
  ],
  [
    "工银券包后台",
    [
      [
        "http://test-icbc-admin.miguatech.com",
        "https://flow.aliyun.com/pipelines/1533692/current",
        "https://flow-openapi.aliyun.com/pipeline/webhook/Rom7nj9aulcmURhN8ig6",
      ],
    ],
  ],
]);

const MINI_PROGRAM_DOC = new Map([
  ["微信开放平台", "https://mp.weixin.qq.com/wxamp/index/index"],
  ["支付宝CN开放平台", "https://open.alipay.com/develop/manage"],
  [
    "小程序自动化部署指引文档",
    "https://aomi.yuque.com/ep7275/hdr02x/ykw1vydem40k88x5",
  ],
]);

const MINI_PROGRAM_SITES = new Map([
  [
    "外卖-微信小程序",
    [
      ["https://flow.aliyun.com/pipelines/2273427/current"],
      ["https://flow.aliyun.com/pipelines/2273439/current"],
      ["https://flow.aliyun.com/pipelines/2273445/current"],
      ["https://flow.aliyun.com/pipelines/2273453/current"],
    ],
  ],
  [
    "外卖-支付宝小程序",
    [
      ["https://flow.aliyun.com/pipelines/2305462/current"],
      ["https://flow.aliyun.com/pipelines/2305650/current"],
      ["https://flow.aliyun.com/pipelines/2305653/current"],
      ["https://flow.aliyun.com/pipelines/2305655/current"],
    ],
  ],
]);

const ENV_MAP = {
  0: "test",
  1: "uat",
  2: "gray",
  3: "prod",
};

export {
  DOCUMENT_URL,
  ENV_MAP,
  AOMI_SITES,
  WORK_SITES,
  MINI_PROGRAM_DOC,
  MINI_PROGRAM_SITES,
};